print("MENCARI SEGITIGA")
print("1. LUAS SEGITIGA")
print("2. KELILING SEGITIGA")
mulai = int(input())
if mulai <= 1:
    print("LUAS SEGITIGA")
    print("Masukan Alas Segitiga")
    alas = int(input())
    print("Masukan Tinggi Segitiga")
    tinggi = int(input())
    print("RUMUS : (L = 1/2 x alas x tinggi)")
    luas = float(1) / 2 * alas * tinggi
    print("L = 1/2 x " + str(alas) + " x " + str(tinggi))
    print("L = " + str(luas) + " cm")
    print("Jadi, Luas Segitiga Adalah " + str(luas) + " cm")
else:
    print("LUAS SEGITIGA")
    print("Masukan Sisi A Segitiga")
    SA = int(input())
    print("Masukan Sisi B Segitiga")
    SB = int(input())
    print("Masukan Sisi C Segitiga")
    SC = int(input())
    print("RUMUS : (K = sisiA + sisiB + sisiC)")
    keliling = SA + SB + SC
    print("K = " + str(SA) + " + " + str(SB) + " + " + str(SC))
    print("K = " + str(keliling) + " cm")
    print("Jadi, Keliling Segitiga Adalah " + str(keliling) + " cm")
print("SELESAI")
